ENH: Add cxx test
slicersalt/ITKShape pull request #12
Opened 2021-03-16 14:30 UTC by tbirdso

2021-03-18 02:13 UTC, thewtex requested changes
👍 One minor tweak, and good to go.

2021-03-18 02:13 UTC, thewtex commented on itk-module.cmake
> +    ITKIOMeshBase
This can go in `TEST_DEPENDS`.

2021-04-01 19:45 UTC, tbirdso commented
Rebased on `main`.

2021-04-05 15:30 UTC, thewtex approved these changes
🐰 🚀

2021-04-05 15:30 UTC, merged